GET http://localhost:3001/api/record
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlcmdpb2JlbHRyYW4iLCJpZCI6IjYxMTUxNzM5Y2MyNjZlMDAxNjJlYzA4ZSIsImlhdCI6MTYyODg0NjM4M30.uNyfy6-hox6IKzbihgi1ytC0114HjPkRkEWapJ8fy3k