DELETE http://localhost:3001/api/record/61444c893dff5e8894a720d9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlcmdpb2JlbHRyYW4iLCJpZCI6IjYxMTUxNzM5Y2MyNjZlMDAxNjJlYzA4ZSIsImlhdCI6MTYyOTI4NzcyMn0._1Ua2Dc39fBPK8hGxnhNU1QRjhoOTZSIsCifFCVk90c
