PUT http://localhost:3001/api/record/6149e0ad8e823829dd215c2d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlcmdpb2JlbHRyYW4iLCJpZCI6IjYxMTUxNzM5Y2MyNjZlMDAxNjJlYzA4ZSIsImlhdCI6MTYyOTI4NzcyMn0._1Ua2Dc39fBPK8hGxnhNU1QRjhoOTZSIsCifFCVk90c
Content-Type: application/json

{
  "entryTime": "17:00",
  "departureTime": "23:30"
}