GET https://papachu-api.herokuapp.com/api/record
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlcmdpb2JlbHRyYW4iLCJpZCI6IjYxMTUxNzM5Y2MyNjZlMDAxNjJlYzA4ZSIsImlhdCI6MTYyODc3MjE1OX0.1Ehb76lECsh5yN40x6BfEC_RykDnXwATqucCTUkqh2k