GET http://localhost:3001/api/record/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhdXZpbGFyIiwiaWQiOiI2MTE1MDkxNTQzOGVjMGZmYjRjYTNkM2MiLCJpYXQiOjE2Mjg3Njg1NTJ9.sLHJyPrychTTM-TDxkpzfO0J1mo3Z5QUWHkDtldIDfQ